# Deep learning model for MNIST dataset
The "Hello World" of deep learning.

In [1]:
from tensorflow.keras.datasets import mnist

Load data encoded as NumPy arrays

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


Train data information

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Test data information

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## Building the neural network

In [9]:
from tensorflow import keras
from tensorflow.keras import layers

The model has two dense layers, the output is a array of 10 probability scores of the current image belonging to one of the 10 digits

In [10]:
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-07-10 21:39:18.501589: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-10 21:39:18.501764: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Training. We select an optimizer, a loss function and a metric to monitor during training and testing

In [11]:
model.compile(optimizer="rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

We preprocess the data to scale between 0 and 1 and reshaping for input layer (60000, 28 * 28)

In [12]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [13]:
# Training step - fitting the model with training data
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5


2022-07-10 21:45:28.906952: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-07-10 21:45:29.314011: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


469/469 [==============================] - 5s 6ms/step - loss: 0.2560 - accuracy: 0.9255
Epoch 2/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1038 - accuracy: 0.9696
Epoch 3/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0690 - accuracy: 0.9788
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0498 - accuracy: 0.9848
Epoch 5/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0378 - accuracy: 0.9887


Testing the model

In [14]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 138ms/step


2022-07-10 21:48:42.511986: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([2.7158981e-10, 5.9046587e-11, 5.2258849e-07, 9.5950663e-06,
       3.4171760e-12, 1.5263609e-09, 7.5968246e-16, 9.9998915e-01,
       5.7444591e-08, 6.7559063e-07], dtype=float32)

In [15]:
predictions[0].argmax()

7

In [16]:
predictions[0][7]

0.99998915

In [17]:
test_labels[0]

7

In [18]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

 27/313 [=>............................] - ETA: 1s - loss: 0.0575 - accuracy: 0.9792

2022-07-10 21:50:28.460775: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


313/313 [==============================] - 1s 4ms/step - loss: 0.0627 - accuracy: 0.9811
test_acc: 0.9811000227928162
